const HYDRATE_STATE = 'HYDRATE_STATE'
const STORE_FOUND_VERSES = 'STORE_FOUND_VERSES'
const TOGGLE_VERSE_SELECTION = 'TOGGLE_VERSE_SELECTION'

export {
  HYDRATE_STATE,
  STORE_FOUND_VERSES,
  TOGGLE_VERSE_SELECTION
}